"""empty message

Revision ID: 783127742d30
Revises: c6dc339c424e
Create Date: 2025-04-03 11:51:08.454955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '783127742d30'
down_revision = 'c6dc339c424e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recording_end_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('recoding_end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recoding_end_time', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('recording_end_time')

    # ### end Alembic commands ###
