"""empty message

Revision ID: a42a3d947b50
Revises: 783127742d30
Create Date: 2025-04-03 12:01:56.694517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a42a3d947b50'
down_revision = '783127742d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('recording_end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recording_end_time', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
