"""empty message

Revision ID: cde2cccef39a
Revises: b74e832d7ffa
Create Date: 2025-04-02 12:30:02.741436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde2cccef39a'
down_revision = 'b74e832d7ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_objects', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videos', schema=None) as batch_op:
        batch_op.drop_column('detected_objects')

    # ### end Alembic commands ###
