"""empty message

Revision ID: e72ead9cd60c
Revises: e93f6dd92508
Create Date: 2025-04-10 17:05:03.798851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72ead9cd60c'
down_revision = 'e93f6dd92508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index('ix_Users_email')
        batch_op.create_index(batch_op.f('ix_Users_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_email'))
        batch_op.create_index('ix_Users_email', ['email'], unique=True)

    # ### end Alembic commands ###
